apiVersion: 1

datasources:
  - name: TimescaleDB
    type: postgres
    access: proxy
    url: timescaledb:5432
    database: zero_trading
    user: zero_user
    # Password is configured via API using scripts/configure_grafana.py
    # Run 'make configure-grafana' after Grafana starts to set the password
    # Grafana provisioning files don't expand ${} environment variables
    secureJsonData:
      password: ""
    jsonData:
      sslmode: disable
      postgresVersion: 1400
      timescaledb: true
    isDefault: true
    editable: true

