apiVersion: 1

datasources:
  - name: TimescaleDB
    type: postgres
    access: proxy
    url: timescaledb:5432
    database: zero_trading
    user: zero_user
    # Password will be set via Grafana UI or environment variable
    # Grafana provisioning doesn't expand ${} variables, so leave editable
    secureJsonData:
      password: ""
    jsonData:
      sslmode: disable
      postgresVersion: 1400
      timescaledb: true
    isDefault: true
    editable: true

